/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lzt_JniTest */

#ifndef _Included_com_lzt_JniTest
#define _Included_com_lzt_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lzt_JniTest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lzt_JniTest_get
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
