/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lzt_JniTest */

#ifndef _Included_com_lzt_JniTest
#define _Included_com_lzt_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lzt_JniTest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lzt_JniTest_get
  (JNIEnv *, jclass);

/*
 * Class:     com_lzt_JniTest
 * Method:    add
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lzt_JniTest_add
  (JNIEnv *, jclass);

/*
 * Class:     com_lzt_JniTest
 * Method:    minus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lzt_JniTest_minus
  (JNIEnv *, jclass);

/*
 * Class:     com_lzt_JniTest
 * Method:    test
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_lzt_JniTest_test
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_lzt_JniTest
 * Method:    reverse
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lzt_JniTest_reverse
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
